install_type : 'package'
package_url: 'https://dl.grafana.com/oss/release/grafana_10.2.0_amd64.deb'
package_checksum: 'f55219c417bf6e430fd655ef7de091c050e960f4a832a7cd0c0ea29868ff9ddd'
grafana_config:
  server:
    #domain: "{{ ansible_host }}"
    #root_url: "%(protocol)://{{ ansible_host }}/grafana/"
    serve_from_sub_path: false