---
- name: install nginx
  hosts: backend
  become: true
  vars_files:
    - proxyvars.yml
  tasks:
  - name: install nginx
    ansible.builtin.apt:
      name: nginx
      update_cache: true
      state: present
  - name: Start service nginx, if not started
    ansible.builtin.service:
      name: nginx
      enabled: yes
      state: started