---
- name: postgresql install
  hosts: database
  become: true
  roles:
  - role: postgresql
    tags: 
    - db

- name: grafana install
  hosts: backend
  become: true
  roles:
  - role: grafana
    tags: 
    - grafana

- name: nginx install
  hosts: loadbalancer, backend
  become: true
  roles:
  - role: nginx
    tags: 
    - nginx
